<?php


namespace Dawn\CustomForm\Inputs;


use Dawn\Labels\Facades\Labels;

class Checkbox extends Field
{
    use Options;
    use Resolve;

    public static $type = 'checkbox';

    public static $typeName = '复选框';


    public function showLabel() : array
    {
        $data = parent::showLabel(); // TODO: Change the autogenerated stub
        $this->options;

        if ($this->options['type'] === 'local') {
            $options = $this->options['data'] ?? [];
            $options = collect($options)->pluck('label', 'value');
            $values  = explode(',', $this->value);
            $labels  = [];
            foreach ($values as $item) {
                $labels[] = $options[$item] ?? '';
            }
            $labels = implode(',', $labels);
        } else {
            $labels = $this->value;
        }

        $data['value'] = $labels;
        $data['type']  = 'text';
        $data['copy']  = false;
        return (Labels::resolve($data))->toArray();
    }
}
