<?php


namespace Dawn\CustomForm\Inputs;


use Dawn\CustomForm\Helpers\RowHelper;
use Dawn\Labels\Facades\Labels;

class Textarea extends Field
{
    use Resolve;
    public static $type     = 'textarea';
    public static $typeName = '文本域';

    public function showLabel() : array
    {
        $data          = parent::showLabel(); // TODO: Change the autogenerated stub
        $data['copy'] = false;
        $data['value'] = '共 '. RowHelper::count($data['value']) .'行 ' .RowHelper::works($data['value']).'个字';
        return (Labels::resolve($data))->toArray();
    }


}
